--------------------------------------------------------------------------------
-- Copyright (c) 1995-2006 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 8.2.02i
--  \   \         Application : xaw2vhdl
--  /   /         Filename : clockselec.vhd
-- /___/   /\     Timestamp : 10/30/2006 10:55:48
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st F:\LCLS\BPM_digital\vhdl\coregen\ClockMux\\clockselec.xaw F:\LCLS\BPM_digital\vhdl\coregen\ClockMux\\clockselec
--Design Name: clockselec
--Device: xc3s400-5pq208
--
-- Module clockselec
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity clockselec is
   port ( U1_CLKIN_IN        : in    std_logic; 
          U1_RST_IN          : in    std_logic; 
          U1_U2_SELECT_IN    : in    std_logic; 
          U2_CLKIN_IN        : in    std_logic; 
          U2_RST_IN          : in    std_logic; 
          U1_CLKIN_IBUFG_OUT : out   std_logic; 
          U1_CLK0_OUT        : out   std_logic; 
          U1_LOCKED_OUT      : out   std_logic; 
          U1_U2_CLK_OUT      : out   std_logic; 
          U2_CLKDV_OUT       : out   std_logic; 
          U2_CLKIN_IBUFG_OUT : out   std_logic; 
          U2_CLK0_OUT        : out   std_logic; 
          U2_CLK2X_OUT       : out   std_logic; 
          U2_LOCKED_OUT      : out   std_logic);
end clockselec;

architecture BEHAVIORAL of clockselec is
   signal GND1               : std_logic;
   signal U1_CLKFB_IN        : std_logic;
   signal U1_CLKIN_IBUFG     : std_logic;
   signal U1_CLK0_BUF        : std_logic;
   signal U2_CLKDV_BUF       : std_logic;
   signal U2_CLKFB_IN        : std_logic;
   signal U2_CLKIN_IBUFG     : std_logic;
   signal U2_CLK0_BUF        : std_logic;
   signal U2_CLK2X_BUF       : std_logic;
   component BUFGMUX
      port ( I0 : in    std_logic; 
             I1 : in    std_logic; 
             S  : in    std_logic; 
             O  : out   std_logic);
   end component;
   
   component DCM
      generic( CLK_FEEDBACK : string :=  "1X";
               CLKDV_DIVIDE : real :=  2.0;
               CLKFX_DIVIDE : integer :=  1;
               CLKFX_MULTIPLY : integer :=  4;
               CLKIN_DIVIDE_BY_2 : boolean :=  FALSE;
               CLKIN_PERIOD : real :=  10.0;
               CLKOUT_PHASE_SHIFT : string :=  "NONE";
               DESKEW_ADJUST : string :=  "SYSTEM_SYNCHRONOUS";
               DFS_FREQUENCY_MODE : string :=  "LOW";
               DLL_FREQUENCY_MODE : string :=  "LOW";
               DUTY_CYCLE_CORRECTION : boolean :=  TRUE;
               FACTORY_JF : bit_vector :=  x"C080";
               PHASE_SHIFT : integer :=  0;
               STARTUP_WAIT : boolean :=  FALSE;
               DSS_MODE : string :=  "NONE");
      port ( CLKIN    : in    std_logic; 
             CLKFB    : in    std_logic; 
             RST      : in    std_logic; 
             PSEN     : in    std_logic; 
             PSINCDEC : in    std_logic; 
             PSCLK    : in    std_logic; 
             DSSEN    : in    std_logic; 
             CLK0     : out   std_logic; 
             CLK90    : out   std_logic; 
             CLK180   : out   std_logic; 
             CLK270   : out   std_logic; 
             CLKDV    : out   std_logic; 
             CLK2X    : out   std_logic; 
             CLK2X180 : out   std_logic; 
             CLKFX    : out   std_logic; 
             CLKFX180 : out   std_logic; 
             STATUS   : out   std_logic_vector (7 downto 0); 
             LOCKED   : out   std_logic; 
             PSDONE   : out   std_logic);
   end component;
   
   component IBUFG
      port ( I : in    std_logic; 
             O : out   std_logic);
   end component;
   
   component BUFG
      port ( I : in    std_logic; 
             O : out   std_logic);
   end component;
   
begin
   GND1 <= '0';
   U1_CLKIN_IBUFG_OUT <= U1_CLKIN_IBUFG;
   U1_CLK0_OUT <= U1_CLKFB_IN;
   U2_CLKIN_IBUFG_OUT <= U2_CLKIN_IBUFG;
   U2_CLK0_OUT <= U2_CLKFB_IN;
   BUFGMUX_INST : BUFGMUX
      port map (I0=>U1_CLK0_BUF,
                I1=>U2_CLK0_BUF,
                S=>U1_U2_SELECT_IN,
                O=>U1_U2_CLK_OUT);
   
   DCM_INST1 : DCM
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 9.80392,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"8080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U1_CLKFB_IN,
                CLKIN=>U1_CLKIN_IBUFG,
                DSSEN=>GND1,
                PSCLK=>GND1,
                PSEN=>GND1,
                PSINCDEC=>GND1,
                RST=>U1_RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>U1_CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>U1_LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   DCM_INST2 : DCM
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 3.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 16.6667,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"8080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>U2_CLKFB_IN,
                CLKIN=>U2_CLKIN_IBUFG,
                DSSEN=>GND1,
                PSCLK=>GND1,
                PSEN=>GND1,
                PSINCDEC=>GND1,
                RST=>U2_RST_IN,
                CLKDV=>U2_CLKDV_BUF,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>U2_CLK0_BUF,
                CLK2X=>U2_CLK2X_BUF,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>U2_LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   U1_CLKIN_IBUFG_INST : IBUFG
      port map (I=>U1_CLKIN_IN,
                O=>U1_CLKIN_IBUFG);
   
   U1_CLK0_BUFG_INST : BUFG
      port map (I=>U1_CLK0_BUF,
                O=>U1_CLKFB_IN);
   
   U2_CLKDV_BUFG_INST : BUFG
      port map (I=>U2_CLKDV_BUF,
                O=>U2_CLKDV_OUT);
   
   U2_CLKIN_IBUFG_INST : IBUFG
      port map (I=>U2_CLKIN_IN,
                O=>U2_CLKIN_IBUFG);
   
   U2_CLK0_BUFG_INST : BUFG
      port map (I=>U2_CLK0_BUF,
                O=>U2_CLKFB_IN);
   
   U2_CLK2X_BUFG_INST : BUFG
      port map (I=>U2_CLK2X_BUF,
                O=>U2_CLK2X_OUT);
   
end BEHAVIORAL;


